In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction import DictVectorizer
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score

import os, sys, pickle
from datetime import date
from sklearn.linear_model import SGDClassifier

In [3]:
dfon = pd.read_csv('C:/Users/jxjsj/Desktop/tianchi/o2ocoupon/ccf_online_stage1_train.csv')

dfoff = pd.read_csv('C:/Users/jxjsj/Desktop/tianchi/o2ocoupon/ccf_offline_stage1_train.csv')

dftest = pd.read_csv('C:/Users/jxjsj/Desktop/tianchi/o2ocoupon/ccf_offline_stage1_test_revised.csv')

In [5]:
X = pd.DataFrame()
offline = dfoff

In [6]:
coupon_id_notnull = offline[offline.Coupon_id.notnull()]

temp = coupon_id_notnull
coupon_consume = temp[temp.Date.notnull()]
coupon_no_consume = temp[temp.Date.isnull()]

user_coupon_consume = coupon_consume.groupby('User_id')

# X['weekday'] = X.Date_received.dt.weekday
# X['day'] = X.Date_received.dt.day

# # 距离优惠券消费次数
# temp = coupon_consume.groupby('Distance').size().to_frame('distance_0')
# X = pd.merge(X, temp, how='left', on='Distance')

# # 距离优惠券不消费次数
# temp = coupon_no_consume.groupby('Distance').size().to_frame('distance_1')
# X = pd.merge(X, temp, how='left', on='Distance')

# # 距离优惠券领取次数
# X['distance_2'] = X.distance_0 + X.distance_1

# # 距离优惠券消费率
# X['distance_3'] = X.distance_0 / X.distance_2

In [10]:
coupon_id_notnull

,User_id,Merchant_id,Coupon_id,Discount_rate,Distance,Date_received,Date
1,1439408,4663,11002.0,150:20,1.0,20160528.0,NaN
2,1439408,2632,8591.0,20:1,0.0,20160217.0,NaN
3,1439408,2632,1078.0,20:1,0.0,20160319.0,NaN
4,1439408,2632,8591.0,20:1,0.0,20160613.0,NaN
6,1439408,2632,8591.0,20:1,0.0,20160516.0,20160613.0
7,1832624,3381,7610.0,200:20,0.0,20160429.0,NaN
8,2029232,3381,11951.0,200:20,1.0,20160129.0,NaN
9,2029232,450,1532.0,30:5,0.0,20160530.0,NaN
10,2029232,6459,12737.0,20:1,0.0,20160519.0,NaN
13,2747744,6901,1097.0,50:10,NaN,20160606.0,NaN
15,196342,1579,10698.0,20:1,1.0,20160606.0,NaN
16,2223968,3381,9776.0,10:5,2.0,20160129.0,NaN
17,73611,2099,12034.0,100:10,NaN,20160207.0,NaN
18,163606,1569,5054.0,200:30,10.0,20160421.0,NaN
19,3273056,4833,7802.0,200:20,10.0,20160130.0,NaN
20,94107,3381,7610.0,200:20,2.0,20160412.0,NaN
22,253750,6901,2366.0,30:5,0.0,20160518.0,NaN
23,253750,8390,7531.0,20:5,0.0,20160327.0,NaN
24,343660,4663,11002.0,150:20,NaN,20160528.0,NaN
25,376492,1041,13490.0,30:5,2.0,20160127.0,NaN
27,1964720,7884,6704.0,20:1,10.0,20160215.0,NaN
31,1113008,3621,2705.0,20:5,0.0,20160524.0,NaN
32,1113008,2277,1495.0,30:10,0.0,20160523.0,NaN
33,1113008,1361,11166.0,20:1,0.0,20160515.0,20160521.0
35,1113008,1361,11166.0,20:1,0.0,20160521.0,NaN
36,1113008,1041,11197.0,30:5,2.0,20160114.0,NaN
37,2881376,5341,111.0,30:5,1.0,20160207.0,NaN
38,2881376,8390,7531.0,20:5,0.0,20160321.0,20160329.0
39,2881376,5341,111.0,30:5,1.0,20160207.0,NaN
41,4061024,2709,2840.0,100:10,10.0,20160129.0,NaN
...,...,...,...,...,...,...,...
1754833,1437872,7706,416.0,100:10,4.0,20160129.0,20160202.0
1754834,1437872,7706,12097.0,100:10,4.0,20160202.0,NaN
1754835,1437872,3381,11951.0,200:20,2.0,20160129.0,NaN
1754839,3400544,6454,14031.0,100:10,2.0,20160131.0,NaN
1754843,98091,1553,10027.0,0.95,10.0,20160510.0,NaN
1754844,457900,7907,13118.0,150:30,NaN,20160418.0,NaN
1754845,2876768,6901,2107.0,30:5,0.0,20160531.0,NaN
1754848,4056416,7177,3469.0,20:1,NaN,20160514.0,NaN
1754849,4056416,2420,10883.0,100:30,NaN,20160613.0,NaN
1754850,179830,3381,1807.0,300:30,0.0,20160124.0,NaN
1754851,179830,4059,7166.0,100:10,7.0,20160124.0,NaN
1754853,179830,6434,10050.0,50:5,1.0,20160123.0,NaN
1754854,179830,6284,4567.0,50:10,1.0,20160124.0,NaN
1754855,179830,6284,7379.0,50:10,1.0,20160124.0,NaN
1754856,179830,3710,13056.0,150:10,4.0,20160124.0,NaN
1754857,179830,2099,12034.0,100:10,1.0,20160124.0,NaN
1754858,179830,4660,1480.0,100:10,0.0,20160125.0,NaN
1754859,179830,5341,7751.0,50:10,0.0,20160123.0,NaN
1754860,179830,7555,17.0,30:5,7.0,20160123.0,NaN
1754861,179830,760,3237.0,20:5,0.0,20160124.0,NaN
1754862,179830,2099,12034.0,100:10,1.0,20160203.0,NaN
1754866,3795296,5341,111.0,30:5,0.0,20160129.0,NaN
1754869,188086,6568,4723.0,30:1,0.0,20160415.0,NaN
1754873,212662,2934,5686.0,30:5,2.0,20160321.0,20160330.0
1754876,212662,3532,5267.0,30:5,1.0,20160322.0,NaN
1754877,212662,3021,3739.0,30:1,6.0,20160504.0,20160508.0
1754878,212662,2934,5686.0,30:5,2.0,20160321.0,20160322.0
1754880,212662,3021,3739.0,30:1,6.0,20160508.0,20160602.0
1754882,752472,7113,1633.0,50:10,6.0,20160613.0,NaN
1754883,752472,3621,2705.0,20:5,0.0,20160523.0,NaN